language: php

php:
  - 5.4
  - 5.5

before_install:
- composer self-update

install:
- composer install --prefer-source --dev

before_script:
- printf "\n" | pecl install imagick

script:
- vendor/bin/phpunit
