language: php

php:
  - 5.4
  - 5.5

before_install:
- composer self-update
- composer global require squizlabs/php_codesniffer:1.5.3

before_script:
- composer install --prefer-source --dev

script:
- phpcs --standard=PSR1 --extensions=php --ignore=vendor/* .
- vendor/bin/phpunit ./tests/Phits/Tests/TestFits.php
